DELETE http://localhost:3001/api/persons/60379d5637bb4ed49544f45e
Content-Type: application/json

###
PUT http://localhost:3001/api/persons/6038b273e552877767398992 HTTP/1.1
content-type: application/json

{
  "number": "123"
}

###
GET http://localhost:3001/api/persons/6038ada5a2f6346e67af10a2